# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonwrapper',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
    ]
