# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('problem', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('good_solutions', models.IntegerField(default=0)),
                ('bad_solutions', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=1)),
                ('optional', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
    ]
