# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_submit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='result',
        ),
        migrations.AddField(
            model_name='submit',
            name='submittedFile',
            field=models.FileField(default='lessons.defaultResult.out', upload_to=''),
        ),
    ]
