# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20160219_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='submittedFile',
            field=models.FileField(upload_to=''),
        ),
    ]
