# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20160219_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='submittedFile',
            field=models.FileField(upload_to='submits'),
        ),
    ]
