# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='correct_solution',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
