# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'lesson')]),
        ),
    ]
