# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_submit_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='inputs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
