# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20160321_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='bad_solutions',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='good_solutions',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='correct_solution',
            field=models.FileField(blank=True, null=True, upload_to='outputs'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='inputs',
            field=models.FileField(blank=True, null=True, upload_to='inputs'),
        ),
    ]
