# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 20:04
from __future__ import unicode_literals

import bcServer.stats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_lessonstat_fun'),
    ]

    
