# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20160321_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstat',
            name='avg_diff',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonstat',
            name='avg_fun',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
