# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20160321_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstat',
            name='avg_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonstat',
            name='avg_fun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
