# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20160321_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstat',
            name='avg_diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonstat',
            name='avg_fun',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
