# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20160326_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_lessonstat',
            unique_together=set([('lesson', 'user')]),
        ),
    ]
