# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_auto_20160326_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_lessonstat',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstat',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonstat',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
