# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_auto_20160330_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_lessonstat',
            name='complete',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'lesson')]),
        ),
    ]
